// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud.DataAccess;

#nullable disable

namespace crud.DataAccess.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20241226133236_add type")]
    partial class addtype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("crud.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            Name = "Product 1-db",
                            Price = 10.0,
                            Quantity = 10,
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            Name = "Product 2-db",
                            Price = 20.0,
                            Quantity = 20,
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            Name = "Product 3-db",
                            Price = 30.0,
                            Quantity = 30,
                            Status = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("crud.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressNo = "42",
                            City = "Kurunegala",
                            Name = "User 1-db",
                            Street = "Street 1",
                            Type = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AddressNo = "33",
                            City = "Colombo",
                            Name = "User 2-db",
                            Street = "Street 2",
                            Type = "admin"
                        },
                        new
                        {
                            Id = 3,
                            AddressNo = "35",
                            City = "Colombo",
                            Name = "User 3-db",
                            Street = "Street 3",
                            Type = "customer"
                        },
                        new
                        {
                            Id = 4,
                            AddressNo = "35",
                            City = "Colombo",
                            Name = "User 4-db",
                            Street = "Street 4",
                            Type = "customer"
                        },
                        new
                        {
                            Id = 5,
                            AddressNo = "44",
                            City = "Galgamuwa",
                            Name = "User 5-db",
                            Street = "Street 4",
                            Type = "customer"
                        });
                });

            modelBuilder.Entity("crud.Models.Product", b =>
                {
                    b.HasOne("crud.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("crud.Models.User", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
